// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './klee-one-d192e144.ttf' with { type: 'url' };
import fullFontUrl from './klee-one.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Klee One Tegaki d192e144',
  fullFamily: 'Klee One',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Klee One Tegaki d192e144'; src: url(${fontUrl}); } @font-face { font-family: 'Klee One'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1160,
  descender: -288,
  glyphData,
  glyphDataById,
  features: ["cjct","dnom","frac","liga","numr","vert","vrt2"],
} as const;

export default bundle;
