// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './suez-one-ac7f1d1c.ttf' with { type: 'url' };
import fullFontUrl from './suez-one.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Suez One Tegaki ac7f1d1c',
  fullFamily: 'Suez One',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Suez One Tegaki ac7f1d1c'; src: url(${fontUrl}); } @font-face { font-family: 'Suez One'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 987,
  descender: -319,
  glyphData,
  glyphDataById,
  features: ["frac","liga","locl"],
} as const;

export default bundle;
