// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './italianno-3dc76002.ttf' with { type: 'url' };
import fullFontUrl from './italianno.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Italianno Tegaki 3dc76002',
  fullFamily: 'Italianno',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Italianno Tegaki 3dc76002'; src: url(${fontUrl}); } @font-face { font-family: 'Italianno'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 800,
  descender: -450,
  glyphData,
  glyphDataById,
  features: ["fina","frac","init","liga","locl","pnum","tnum"],
} as const;

export default bundle;
