// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './amiri-7df37680.ttf' with { type: 'url' };
import fullFontUrl from './amiri.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Amiri Tegaki 7df37680',
  fullFamily: 'Amiri',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Amiri Tegaki 7df37680'; src: url(${fontUrl}); } @font-face { font-family: 'Amiri'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1124,
  descender: -634,
  glyphData,
  glyphDataById,
  features: ["ccmp","dnom","fina","init","liga","locl","medi","numr","pnum","rlig"],
} as const;

export default bundle;
