// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './parisienne-3dc76002.ttf' with { type: 'url' };
import fullFontUrl from './parisienne.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Parisienne Tegaki 3dc76002',
  fullFamily: 'Parisienne',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Parisienne Tegaki 3dc76002'; src: url(${fontUrl}); } @font-face { font-family: 'Parisienne'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 2048,
  ascender: 1875,
  descender: -915,
  glyphData,
  glyphDataById,
  features: ["frac","liga"],
} as const;

export default bundle;
