// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './tillana-12e48378.ttf' with { type: 'url' };
import fullFontUrl from './tillana.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Tillana Tegaki 12e48378',
  fullFamily: 'Tillana',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Tillana Tegaki 12e48378'; src: url(${fontUrl}); } @font-face { font-family: 'Tillana'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1158,
  descender: -484,
  glyphData,
  glyphDataById,
  features: ["abvs","akhn","blwf","blws","half","haln","liga","nukt","pres","psts","rkrf","rphf","vatu"],
} as const;

export default bundle;
