// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './caveat-3dc76002.ttf' with { type: 'url' };
import fullFontUrl from './caveat.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Caveat Tegaki 3dc76002',
  fullFamily: 'Caveat',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Caveat Tegaki 3dc76002'; src: url(${fontUrl}); } @font-face { font-family: 'Caveat'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 960,
  descender: -300,
  glyphData,
  glyphDataById,
  features: ["calt","frac","liga"],
} as const;

export default bundle;
